

services:
  server:
    build:
      context: .
      dockerfile: LogHttpServer/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    
