name: Build Windows

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: CMake
        shell: pwsh
        run: |
          mkdir build
          cd build
          cmake -G "Ninja" -A x64 -D CMAKE_BUILD_TYPE=Release ..

      - name: Build
        shell: pwsh
        run: |
          cd build
          cmake --build . --config Release

      - name: Show Build Directory Contents
        shell: pwsh
        run: |
          ls
          cd build
          ls
          cd example
          ls
          cd Release
          ls
