
name: Build Windows

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build cpplog
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target cpplog