name: Build Windows

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: CMake
        shell: pwsh
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" -A x64 -D CMAKE_BUILD_TYPE=Release ..

      - name: Build
        shell: pwsh
        run: |
          cd build
          cmake --build . Release
