name: Build Windows with MinGW

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up MinGW
        run: |
          choco install mingw
          echo "Adding MinGW to PATH"
          echo "$(C:/ProgramData/chocolatey/bin/mingw64/bin)" >> $GITHUB_PATH

      - name: Configure CMake with MinGW
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++

      - name: Build cpplog
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target cpplog

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target unit_tests

      - name: Run Google Tests
        working-directory: ${{github.workspace}}/build
        run: .\unit_tests.exe
